version: '3.8'

services:
  sling-hockey:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - sling-hockey-network

networks:
  sling-hockey-network:
    driver: bridge