name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd types && npm ci && cd ..
        cd server && npm ci && cd ..
        cd client && npm ci && cd ..
    
    - name: Build types
      run: cd types && npm run build
    
    - name: Lint and Test Server
      run: |
        cd server
        npm test
    
    - name: Build Server
      run: cd server && npm run build
    
    - name: Test Client
      run: |
        cd client
        npm test
    
    - name: Build Client
      run: cd client && npm run build

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Build all packages
      run: |
        npm ci
        npm run build
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          server/dist
          client/dist
        retention-days: 7